### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by YrChen1001** [MineYuanlu/yuanluServerDo#1]
Dose it support paper 1.19?

**Comment by MineYuanlu** [comment]
I haven't tested all versions one by one, but many servers use 1.19 at present.

No version features are used in the design, so I think it can support any version. If you find any problems in 1.7.10 and later versions, you can tell me.

**Comment by YrChen1001** [comment]
`[17:31:11 INFO]: [yuanluServerDo] Loading yuanluServerDo v1.2.0-SNAPSHOT
[17:31:11 WARN]: java.nio.file.NoSuchFileException: C:\Server\1.18.2%20-%20Survival1\plugins\yuanluServerDo.jar
[17:31:11 WARN]:        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[17:31:11 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[17:31:11 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[17:31:11 WARN]:        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
[17:31:11 WARN]:        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
[17:31:11 WARN]:        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
[17:31:11 WARN]:        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
[17:31:11 WARN]:        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
[17:31:11 WARN]:        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
[17:31:11 WARN]:        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
[17:31:11 WARN]:        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
[17:31:11 WARN]:        at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
[17:31:11 WARN]:        at java.base/java.util.jar.JarFile.<init>(JarFile.java:318)
[17:31:11 WARN]:        at java.base/java.util.jar.JarFile.<init>(JarFile.java:257)
[17:31:11 WARN]:        at yuanluServerDo.jar//yuan.plugins.serverDo.bukkit.PackageUtil.getClassNameByJar(PackageUtil.java:104)
[17:31:11 WARN]:        at yuanluServerDo.jar//yuan.plugins.serverDo.bukkit.PackageUtil.getClassName(PackageUtil.java:54)
[17:31:11 WARN]:        at yuanluServerDo.jar//yuan.plugins.serverDo.bukkit.cmds.CommandManager.init(CommandManager.java:76)
[17:31:11 WARN]:        at yuanluServerDo.jar//yuan.plugins.serverDo.bukkit.Main.onLoad(Main.java:309)
[17:31:11 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:427)
[17:31:11 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:278)
[17:31:11 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1122)
[17:31:11 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[17:31:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by MineYuanlu** [comment]
This error was fixed in the [`1.2.0-SNATHOST-5`](https://github.com/MineYuanlu/yuanluServerDo/releases) version and later because the file path contains special characters (spaces, brackets, etc., which are caused by spaces here)

**Comment by YrChen1001** [comment]
Which version should I use? bungee cord and paper.
![image](https://user-images.githubusercontent.com/99790174/182363123-3f2789d8-99e3-48ca-bd4a-67d421aae8d0.png)

**Comment by MineYuanlu** [comment]
> Which version should I use? bungee cord and paper. 

You can only download [`yuanluServerDo-bukkit-bungeecord-1.2.0-SNATHOST-7.jar`](https://github.com/MineYuanlu/yuanluServerDo/releases/download/1.2.0-SNATHOST-7/yuanluServerDo-bukkit-bungeecord-1.2.0-SNATHOST-7.jar), and then use this file on `bungeerecord` and `paper`

Or you can download [`yuanluServerDo-bungeecord-1.2.0-SNATHOST-7.jar`](https://github.com/MineYuanlu/yuanluServerDo/releases/download/1.2.0-SNATHOST-7/yuanluServerDo-bungeecord-1.2.0-SNATHOST-7.jar) and [`yuanluServerDo-bukkit-1.2.0-SNATHOST-7.jar`](https://github.com/MineYuanlu/yuanluServerDo/releases/download/1.2.0-SNATHOST-7/yuanluServerDo-bukkit-1.2.0-SNATHOST-7.jar) for `bungeerecord` and `paper` respectively

**Comment by YrChen1001** [comment]
is that will cover essentials 's command when server restart?

**Comment by YrChen1001** [comment]
when player use command , won't show player name.

**Comment by MineYuanlu** [comment]
Under normal circumstances, there is a player name completion feature. Can you provide your contact information? I need to collect error information.
As for the /back feature, it really cannot be used and may be repaired in the future, but I am busy with other things at present.

**Comment by YrChen1001** [comment]
Discord:`Patronsaint1#4337`
WeChat:`yrchen1001`
